name: Quant11 Backend-Prod-Deploy

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Extract Git SHA
    - name: Extract Git SHA
      id: extract_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: list out present working directory
      run: ls -la
      
    - name: Build docker image and push with caching
      id: build-image
      run: |
        docker buildx build --push \
          -t ${{ steps.login-ecr.outputs.registry }}/quant11-production-backend:${{ steps.extract_sha.outputs.sha }} \
          --cache-to mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ steps.login-ecr.outputs.registry }}/quant11-production-backend-cache-image \
          --cache-from type=registry,ref=${{ steps.login-ecr.outputs.registry }}/quant11-production-backend-cache-image \
          -f Dockerfile .

    - name: Set image output
      id: set-image-output
      run: echo "image=${{ steps.login-ecr.outputs.registry }}/quant11-production-backend:${{ steps.extract_sha.outputs.sha }}" >> $GITHUB_OUTPUT

    # Update New Image In Task Definition 
    # - name: Update New image in Task Definition
    #   id: backend-task-def
    #   uses: aws-actions/amazon-ecs-render-task-definition@v1
    #   with:
    #     task-definition: ecs-task-definitions/production-backend-task-definition.json
    #     container-name: Quant11-Backend
    #     image: ${{ steps.set-image-output.outputs.image }}

    # # Deploy Backend Task Definition to ECS 
    # - name: Deploying Quant11-Backend Task Definition to ECS 
    #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
    #   with:
    #     task-definition: ${{ steps.backend-task-def.outputs.task-definition }}
    #     service: Quant11-Back
    #     cluster: Quant11-Production
    #     wait-for-service-stability: true
